# Generated by Django 5.2.15 on 2026-06-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_proifile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proifile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_vrrified',
            new_name='phone_verified',
        ),
    ]
